name: lambdamail
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - cmake>=3.10
  - make
  - libcurl
  - jsoncpp
  - pkg-config
  - autoconf
  - automake
  - libtool
  - compilers
  # Development tools
  - ninja
  - ccache
  - sfml
